"""Added new fields to Toilet model

Revision ID: 29682bf6fd82
Revises: 04bb2a54044c
Create Date: 2024-04-15 16:57:08.537021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29682bf6fd82'
down_revision = '04bb2a54044c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toilet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('timeOfDay', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('openingHours', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('buildingNumber', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('postcode', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('lastUploaded', sa.DateTime(), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('accessibility')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toilet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accessibility', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.drop_column('lastUploaded')
        batch_op.drop_column('postcode')
        batch_op.drop_column('street')
        batch_op.drop_column('buildingNumber')
        batch_op.drop_column('openingHours')
        batch_op.drop_column('timeOfDay')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
